<?php

$skills = array(
	array(
		"name"=>"HTML",
		"iconUrl"=>"assets/html.png",
		"iconSize"=>60,
		"level"=>"great"
	),
	array(
		"name"=>"CSS",
		"iconUrl"=>"assets/css.png",
		"iconSize"=>60,
		"level"=>"great"
	),
	array(
		"name"=>"JavaScript",
		"iconUrl"=>"assets/js.png",
		"iconSize"=>60,
		"level"=>"great"
	),
	array(
		"name"=>"NodeJS",
		"iconUrl"=>"assets/nodejs.png",
		"iconSize"=>100,
		"level"=>"medium"
	),
	array(
		"name"=>"PHP",
		"iconUrl"=>"assets/php.png",
		"iconSize"=>80,
		"level"=>"great"
	),
	array(
		"name"=>"Laravel",
		"iconUrl"=>"assets/laravel.png",
		"iconSize"=>60,
		"level"=>"great"
	),
	array(
		"name"=>"Go",
		"iconUrl"=>"assets/golang.png",
		"iconSize"=>70,
		"level"=>"great"
	),
	array(
		"name"=>"ASP.NET",
		"iconUrl"=>"assets/asp.png",
		"iconSize"=>80,
		"level"=>"great"
	),
	array(
		"name"=>"Spring",
		"iconUrl"=>"assets/spring.png",
		"iconSize"=>60,
		"level"=>"good"
	),
	array(
		"name"=>"Vue Js",
		"iconUrl"=>"assets/vue.png",
		"iconSize"=>60,
		"level"=>"medium"
	),
	array(
		"name"=>"C#",
		"iconUrl"=>"assets/cs.png",
		"iconSize"=>100,
		"level"=>"great"
	),
	array(
		"name"=>"Java",
		"iconUrl"=>"assets/java.png",
		"iconSize"=>80,
		"level"=>"great"
	),
	array(
		"name"=>"Android Native",
		"iconUrl"=>"assets/android.png",
		"iconSize"=>100,
		"level"=>"great"
	),
	array(
		"name"=>"Flutter",
		"iconUrl"=>"assets/flutter.png",
		"iconSize"=>60,
		"level"=>"medium"
	),
	array(
		"name"=>"Unity",
		"iconUrl"=>"assets/unity.png",
		"iconSize"=>60,
		"level"=>"good"
	),
	array(
		"name"=>"SQL",
		"iconUrl"=>"assets/sql.png",
		"iconSize"=>70,
		"level"=>"great"
	),
	array(
		"name"=>"MySQL",
		"iconUrl"=>"assets/mysql.png",
		"iconSize"=>80,
		"level"=>"great"
	),
	array(
		"name"=>"Redis",
		"iconUrl"=>"assets/redis.png",
		"iconSize"=>100,
		"level"=>"medium"
	),
	array(
		"name"=>"MongoDB",
		"iconUrl"=>"assets/mongo.png",
		"iconSize"=>80,
		"level"=>"medium"
	),
	array(
		"name"=>"PostgreSQL",
		"iconUrl"=>"assets/pg.png",
		"iconSize"=>100,
		"level"=>"great"
	),
	array(
		"name"=>"PubSub",
		"iconUrl"=>"assets/pubsub.png",
		"iconSize"=>60,
		"level"=>"medium"
	),
	array(
		"name"=>"Watermill",
		"iconUrl"=>"assets/watermil.png",
		"iconSize"=>60,
		"level"=>"medium"
	),
	array(
		"name"=>"BigQuery",
		"iconUrl"=>"assets/bigquery.png",
		"iconSize"=>60,
		"level"=>"great"
	),
	array(
		"name"=>"Elasticsearch",
		"iconUrl"=>"assets/elastic.png",
		"iconSize"=>60,
		"level"=>"good"
	),
	array(
		"name"=>"Rabbit MQ",
		"iconUrl"=>"assets/mq.png",
		"iconSize"=>60,
		"level"=>"good"
	)
);